spring.application.name=eshop

server.port = 8085
spring.datasource.url=jdbc:h2:mem:eshop_db
spring.jpa.show-sql=true
spring.h2.console.enabled = true
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=user
spring.datasource.password=password
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.web.error.include-message=always
spring.web.error.include-binding-errors=always
spring.web.cors.allowed-origins=http://localhost:5173