spring.application.name=eshop


server.port = 8085
spring.datasource.url=jdbc:h2:mem:eshop_db
spring.jpa.show-sql=true
spring.h2.console.enabled = true
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=user
spring.datasource.password=password
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.web.error.include-message=always
spring.web.error.include-binding-errors=always
spring.web.cors.allowed-origins=http://localhost:5173

#JWT secret key
security.jwt.secret-key=${JWT_SECRET_KEY:1L0YYXHDoABh5VlzTt8Ri6F4043S2qr4IzpBd89PXTcEz }
security.jwt.expiration-time=86400000

#Mail properties
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${SUPPORT_EMAIL:usersupporteshop@gmail.com}
spring.mail.password=${SUPPORT_PASSWORD:gwru memb bdli vrc}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true


